<img align="left" src="https://lever-client-logos.s3.amazonaws.com/864372b1-534c-480e-acd5-9711f850815c-1524247202159.png" width=200>
<br></br>
<br></br>

# Neural Networks

## *Data Science Unit 4 Sprint 2 Assignment 1*

## Define the Following:
You can add image, diagrams, whatever you need to ensure that you understand the concepts below.

### Input Layer:
The input layer is the part of our data that the neural network is exposed to and interacts with. Each input node is typically assigned to one feature.

### Hidden Layer:
The magic of modern neural networks; any layer between input and output layer. The data can not be accessed or directly interact with in this layer. It is passed through obscured to the output.

### Output Layer:
The output layer puts vector values suitable to the type of problem we're trying to assess (regression, classification, etc). They have a node for each type of output (for example, binary classification will have a single output node (probability)).

### Neuron:
Neurons / Nodes receive inputs and pass on the signal to the next layer of nodes if a certain threshold is met.

### Weight:
The weight gives us the range of motion to move up and down the equation. Each step along the way, each layer affects the next layer by using the weighted sum of our inputs (plus bias). One way to think of weights is the strength of connection between nodes.

### Activation Function:
Activation functions determine how much signal is sent from the previous layer to the next. Hidden and output layers may contain activation functions, while input layers don't.

### Node Map:
A node map is a visual diagram that serves as a representation of the neural network's architecture. They are used because the equations to represent the neural network are so complicated that it would be painstakingly hard to read and interpret what is going on within them.

### Perceptron:
A perceptron is the simplest version of a neural network. It's a single node with nothing else but the input. It will take the inputs, calculate with weight, sum up all predictions, then pass the sum to the activation function. The result of this will be our final value.

## Inputs -> Outputs

### Explain the flow of information through a neural network from inputs to outputs. Be sure to include: inputs, weights, bias, and activation functions. How does it all flow from beginning to end?

The neural network takes the input layers, and multiples the weight and add the bias to the inputs. These are then sent to the activation function, which determines how much signal is passed on to the next layer. This is repeated through the hidden layers until the output layer is reached, at which point there will be a node for each type of output.

## Write your own perceptron code that can correctly classify (99.0% accuracy) a NAND gate. 

| x1 | x2 | y |
|----|----|---|
| 0  | 0  | 1 |
| 1  | 0  | 1 |
| 0  | 1  | 1 |
| 1  | 1  | 0 |

In [1]:
import pandas as pd
import numpy as np
data = { 'x1': [0,1,0,1],
         'x2': [0,0,1,1],
         'y':  [1,1,1,0]
       }

df = pd.DataFrame.from_dict(data).astype('int')

values = np.asarray(df.values)

In [2]:
# Sigmoid activation function + derivative for updating weights

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    sx = sigmoid(x)
    return sx * (1 - sx)

In [3]:
# First, we need to initialize random weights for our inputs (3 total)
weights = 2 * np.random.random((3, 1)) - 1
print('Randomized Weights: \n', weights)

Randomized Weights: 
 [[0.35324576]
 [0.19921128]
 [0.24539473]]


In [4]:
# Now, let's calculate the weighted sums of inputs and weights.
weighted_sums = np.dot(values, weights)
print('Weighted Sums: \n', weighted_sums)

Weighted Sums: 
 [[0.24539473]
 [0.59864048]
 [0.444606  ]
 [0.55245703]]


In [5]:
# Now we need to output the activated value at the end of 1 training epoch.
activated_outputs = sigmoid(weighted_sums)
print('Predicted Probability: \n', activated_outputs)

Predicted Probability: 
 [[0.56104266]
 [0.64534521]
 [0.609356  ]
 [0.63470545]]


In [6]:
# Now, we need to calculate our error.
error = values - activated_outputs
print(error)

[[-0.56104266 -0.56104266  0.43895734]
 [ 0.35465479 -0.64534521  0.35465479]
 [-0.609356    0.390644    0.390644  ]
 [ 0.36529455  0.36529455 -0.63470545]]


In [7]:
# Make adjustments through backprop
adjustments = error + sigmoid_derivative(weighted_sum)
print(adjustments)

NameError: name 'weighted_sum' is not defined

In [ ]:
# Update weights based upon gradient descent.
weights += np.dot(df, adjustments)
print(weights)

## Implement your own Perceptron Class and use it to classify a binary dataset: 
- [The Pima Indians Diabetes dataset](https://raw.githubusercontent.com/ryanleeallred/datasets/master/diabetes.csv) 

You may need to search for other's implementations in order to get inspiration for your own. There are *lots* of perceptron implementations on the internet with varying levels of sophistication and complexity. Whatever your approach, make sure you understand **every** line of your implementation and what its purpose is.

In [ ]:
diabetes = pd.read_csv('https://raw.githubusercontent.com/ryanleeallred/datasets/master/diabetes.csv')
diabetes.head()

Although neural networks can handle non-normalized data, scaling or normalizing your data will improve your neural network's learning speed. Try to apply the sklearn `MinMaxScaler` or `Normalizer` to your diabetes dataset. 

In [ ]:
from sklearn.preprocessing import MinMaxScaler, Normalizer

feats = list(diabetes)[:-1]

X = ...

In [ ]:
##### Update this Class #####

class Perceptron:
    
    def __init__(self, niter = 10):
        self.niter = niter
    
    def __sigmoid(self, x):
        return None
    
    def __sigmoid_derivative(self, x):
        return None

    def fit(self, X, y):
    """Fit training data
    X : Training vectors, X.shape : [#samples, #features]
    y : Target values, y.shape : [#samples]
    """

        # Randomly Initialize Weights
        weights = ...

        for i in range(self.niter):
            # Weighted sum of inputs / weights

            # Activate!

            # Cac error

            # Update the Weights


    def predict(self, X):
    """Return class label after unit step"""
        return None

## Stretch Goals:

- Research "backpropagation" to learn how weights get updated in neural networks (tomorrow's lecture). 
- Implement a multi-layer perceptron. (for non-linearly separable classes)
- Try and implement your own backpropagation algorithm.
- What are the pros and cons of the different activation functions? How should you decide between them for the different layers of a neural network?