<img align="left" src="https://lever-client-logos.s3.amazonaws.com/864372b1-534c-480e-acd5-9711f850815c-1524247202159.png" width=200>
<br></br>
<br></br>

# Neural Networks

## *Data Science Unit 4 Sprint 2 Assignment 1*

## Define the Following:
You can add image, diagrams, whatever you need to ensure that you understand the concepts below.

### Input Layer:
The input layer is the *only* part of our data that the neural network is exposed to and interacts with. Each input node is typically assigned to one feature. It is the first layer within the neural network.

### Hidden Layer:
The magic of modern neural networks; any layer between input and output layer. The data can not be accessed or directly interact with in this layer. It is passed through obscured to the output, which may take the form of another hidden layer, or alternatively, the output layer.

### Output Layer:
The output layer puts vector values suitable to the type of problem we're trying to assess (regression, classification, etc). They have a node for each type of output (for example, binary classification will have a single output node (probability)). This can be thought of as the layer that, as the name implies, outputs the results from the neural network.

### Neuron:
Neurons / Nodes receive inputs and pass on the signal to the next layer of nodes if a certain threshold is met. Each layer contains a specified number of nodes.

### Weight:
The weight gives us the range of motion to move up and down the equation. Each step along the way, each layer affects the next layer by using the weighted sum of our inputs (plus bias). One way to think of weights is the strength of connection between nodes.

### Activation Function:
Activation functions determine how much signal is sent from the previous layer to the next. Activation functions are critical to the neural network's performance and are one of the countless parameters that can be tuned using a GridSearchCV or RandomizedSearchCV.

### Node Map:
A node map is a visual diagram that serves as a representation of the neural network's architecture. They are used because the equations to represent the neural network are so complicated that it would be painstakingly hard, if not impossible, and most *certainly* time-consuming to read and interpret what is going on within them.

### Perceptron:
A perceptron is the simplest version of a neural network. It's a single node with nothing else but the input. It will take the inputs, calculate with weight, sum up all predictions, then pass the sum to the activation function. The result of this will be our final value. There are also multi-layered perceptrons which are actually what solved the neural network issue of linear seperability (refer to [XOR Gate](https://en.wikipedia.org/wiki/XOR_gate))

## Inputs -> Outputs

### Explain the flow of information through a neural network from inputs to outputs. Be sure to include: inputs, weights, bias, and activation functions. How does it all flow from beginning to end?

The neural network takes the input layers, and multiples the weight and add the bias to the inputs. These are then sent to the activation function, which determines how much signal is passed on to the next layer. This is repeated through the hidden layers until the output layer is reached, at which point there will be a node for each type of output.

## Write your own perceptron code that can correctly classify (99.0% accuracy) a NAND gate. 

| x1 | x2 | y |
|----|----|---|
| 0  | 0  | 1 |
| 1  | 0  | 1 |
| 0  | 1  | 1 |
| 1  | 1  | 0 |

In [1]:
import pandas as pd
import numpy as np
data = { 'x1': [0,1,0,1],
         'x2': [0,0,1,1],
         'y':  [1,1,1,0]
       }

df = pd.DataFrame.from_dict(data).astype('int')
df['bias'] = [1,1,1,1]  # Adding column for bias.

df.head()

x1  x2  y  bias
0   0   0  1     1
1   1   0  1     1
2   0   1  1     1
3   1   1  0     1

In [0]:
correct_outputs = [[0], [0], [1], [1]]

In [0]:
# Sigmoid activation function + derivative for updating weights

def sigmoid(x):
  '''Base sigmoid activation function'''
  return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
  '''Sigmoid derivative activation function'''
  sx = sigmoid(x)
  return sx * (1 - sx)

### Split Up Individually For Comprehension

In [4]:
# First, we need to initialize random weights for our inputs (3 total)
weights = 2 * np.random.random((4,1)) - 1
print('Randomized Weights: \n', weights)

Randomized Weights: 
 [[-0.12555538]
 [-0.69626632]
 [-0.94980346]
 [ 0.24802523]]


In [5]:
# Now, let's calculate the weighted sums of inputs and weights.

weighted_sums = np.dot(df, weights)  # Dot product of our dataframe and our weights will give us our weighted sums
print('Weighted Sums: \n', weighted_sums)

Weighted Sums: 
 [[-0.70177823]
 [-0.82733361]
 [-1.39804455]
 [-0.57379647]]


In [6]:
# Now we need to output the activated value at the end of 1 training epoch. These are our predicted values.

activated_outputs = sigmoid(weighted_sums)  # Apply sigmoid function to our weighted sums to attain our activated outputs
print('Predicted Probability: \n', activated_outputs)

Predicted Probability: 
 [[0.33141809]
 [0.30420916]
 [0.1981266 ]
 [0.36036127]]


In [7]:
# Now, we need to calculate our error. This can be done by subtracting our predicted outputs by our correct outputs.

error = correct_outputs - activated_outputs
print('Error: \n', error)

Error: 
 [[-0.33141809]
 [-0.30420916]
 [ 0.8018734 ]
 [ 0.63963873]]


In [8]:
# Make adjustments through backpropagation

adjustments = error + sigmoid_derivative(weighted_sums)  # Make adjustments for weight updates.
print('Adjustments: \n', adjustments)

Adjustments: 
 [[-0.10983795]
 [-0.09254321]
 [ 0.96074585]
 [ 0.87013975]]


In [9]:
# Update weights based upon our gradient descent.
weights += np.dot(df.T, adjustments)  # Calculating new weights to update model.
print(weights)

[[ 0.65204116]
 [ 1.13461929]
 [-0.19143877]
 [ 1.87652967]]


### For Loop to Put it All Together

In [10]:
for iteration in range(10000):
    
    # Weighted sum of inputs / weights
    weighted_sum = np.dot(df, weights)
    
    # Activation function
    activated_output = sigmoid(weighted_sum)
    
    # Calculate error
    error = correct_outputs - activated_output
    
    # Calculate adjustments
    adjustments = error * sigmoid_derivative(weighted_sum)
    
    # Update the weights
    weights += np.dot(df.T, adjustments)

print(f'Predicted Values: \n{activated_output}')
print(f'Weights: \n{weights}')
print(f'Error: \n{error}')

Predicted Values: 
[[0.01091517]
 [0.00293897]
 [0.98992491]
 [0.99888368]]
Weights: 
[[-1.32013522]
 [ 9.09429087]
 [-3.52919175]
 [-0.97748542]]
Error: 
[[-0.01091517]
 [-0.00293897]
 [ 0.01007509]
 [ 0.00111632]]




## Implement your own Perceptron Class and use it to classify a binary dataset: 
- [The Pima Indians Diabetes dataset](https://raw.githubusercontent.com/ryanleeallred/datasets/master/diabetes.csv) 

You may need to search for other's implementations in order to get inspiration for your own. There are *lots* of perceptron implementations on the internet with varying levels of sophistication and complexity. Whatever your approach, make sure you understand **every** line of your implementation and what its purpose is.

In [11]:
diabetes = pd.read_csv('https://raw.githubusercontent.com/ryanleeallred/datasets/master/diabetes.csv')
diabetes.head()

Pregnancies  Glucose  BloodPressure  ...  DiabetesPedigreeFunction  Age  Outcome
0            6      148             72  ...                     0.627   50        1
1            1       85             66  ...                     0.351   31        0
2            8      183             64  ...                     0.672   32        1
3            1       89             66  ...                     0.167   21        0
4            0      137             40  ...                     2.288   33        1

[5 rows x 9 columns]

Although neural networks can handle non-normalized data, scaling or normalizing your data will improve your neural network's learning speed. Try to apply the sklearn `MinMaxScaler` or `Normalizer` to your diabetes dataset. 

In [12]:
from sklearn.preprocessing import MinMaxScaler, Normalizer
from sklearn.model_selection import train_test_split

feats = list(diabetes)[:-1]  # List of features (All columns minus the outcome)

transformer = Normalizer().fit(diabetes[feats])  # Instantiate / Fit the Normalizer.
X = transformer.transform(diabetes[feats])  # Transform using the fit.
y = diabetes['Outcome'].values  # Defining our target.

# Train-Test-Split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

print(f'''Train Shapes:
X (Features): {X_train.shape}
y (Target): {y_train.shape}
''')

print(f'''Test Shapes:
X (Features): {X_test.shape}
y (Target): {y_test.shape}
''')

Train Shapes:
X (Features): (514, 8)
y (Target): (514,)

Test Shapes:
X (Features): (254, 8)
y (Target): (254,)



In [0]:
class Perceptron:
    
    def __init__(self, niter=100):  # Constructor
        self.niter = niter
    
    def __sigmoid(self, x):
      """Sigmoid activation function"""
      return 1 / (1 + np.exp(-x))
    
    def __sigmoid_derivative(self, x):
      """Sigmoid Derivative for Backpropagation"""
      sx = sigmoid(x)
      return sx * (1 - sx)

    def fit(self, X, y):  # This will be our fit method.
      """Fit training data
      X : Training vectors, X.shape : [#samples, #features]
      y : Target values, y.shape : [#samples]
      """

        # Randomly Initialize Weights
      self.weights = 2 * np.random.random((8,1)) - 1  # Using self because the weights will be needed in the predict method.

      for i in range(self.niter):  # Range of the number of iterations.

          # Weighted sum of inputs / weights using dot product.
            weighted_sum = np.dot(X, self.weights)

          # Activate function.
            activated_output = self.__sigmoid(weighted_sum)

          # Calculate error.
            error = y - activated_output

          # Make adjustments with sigmoid derivative function.
            adjustments = error * self.__sigmoid_derivative(weighted_sum)

          # Update the weights in accordance to adjustments.
            self.weights = self.weights + np.dot(X.T, adjustments)

      return self

    def predict(self, X):
          """Make predictions of class labels"""
          weighted_sum = np.dot(X, self.weights)  # We're using the weighted sum again...
          activated_output = self.__sigmoid(weighted_sum)  #... to make predictions.
          return np.round(activated_output)  # Note to self: must use numpy to round ndarray - returns predicted values.

In [0]:
pn = Perceptron()  # Instantiate our perceptron

pn.fit(X, y)  # Fit our model
y_pred = pn.predict(X_test)

In [15]:
y_pred  # What would be the best way to measure accuracy here?

array([[1., 0., 1., ..., 0., 1., 0.],
       [1., 0., 1., ..., 0., 1., 0.],
       [1., 0., 1., ..., 0., 1., 0.],
       ...,
       [1., 0., 1., ..., 0., 1., 0.],
       [1., 0., 1., ..., 0., 1., 0.],
       [1., 0., 1., ..., 0., 1., 0.]])

## Stretch Goals:

- Research "backpropagation" to learn how weights get updated in neural networks (tomorrow's lecture). ✔
- Implement a multi-layer perceptron. (for non-linearly separable classes) ✔
- Try and implement your own backpropagation algorithm.
- What are the pros and cons of the different activation functions? How should you decide between them for the different layers of a neural network? ✔

### Strech Goal: Backpropagation (Examples, and high-level overview)

Backpropagation is a way to update weights. There are different options, including SGD and other optimizers such as adam, nadam, and adamax that use different techniques to best optimize the effect of backpropagation.

### Stretch Goal: Multi-Layered Perceptron

In [0]:
# Defining features / target

features = df[['x1', 'x2', 'bias']].values
target = df['y'].values

In [17]:
from tensorflow.keras.layers import Dense
from tensorflow.keras.models import Sequential

model1 = Sequential()

model1.add(Dense(3, activation='sigmoid', input_dim=features.shape[1], name='InputLayer'))
model1.add(Dense(2, activation='sigmoid', name='HiddenLayerMLP'))
model1.add(Dense(1, activation='sigmoid', name='OutputLayer'))

model1.compile(optimizer='adamax', loss='binary_crossentropy', metrics=['accuracy'])

model1.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
InputLayer (Dense)           (None, 3)                 12        
_________________________________________________________________
HiddenLayerMLP (Dense)       (None, 2)                 8         
_________________________________________________________________
OutputLayer (Dense)          (None, 1)                 3         
Total params: 23
Trainable params: 23
Non-trainable params: 0
_________________________________________________________________


In [18]:
print(f'''Input values:
{features}
Shape: {features.shape}
''')

print(f'''Values to predict:
{target}
Shape: {target.shape}''')

Input values:
[[0 0 1]
 [1 0 1]
 [0 1 1]
 [1 1 1]]
Shape: (4, 3)

Values to predict:
[1 1 1 0]
Shape: (4,)


In [19]:
model1.fit(features, target, epochs=250)  # Let's fit our model :)

Epoch 1/250
1/1 [==============================] - 0s 1ms/step - loss: 0.5858 - accuracy: 0.7500
Epoch 2/250
1/1 [==============================] - 0s 1ms/step - loss: 0.5855 - accuracy: 0.7500
Epoch 3/250
1/1 [==============================] - 0s 947us/step - loss: 0.5852 - accuracy: 0.7500
Epoch 4/250
1/1 [==============================] - 0s 2ms/step - loss: 0.5849 - accuracy: 0.7500
Epoch 5/250
1/1 [==============================] - 0s 1ms/step - loss: 0.5846 - accuracy: 0.7500
Epoch 6/250
1/1 [==============================] - 0s 1ms/step - loss: 0.5843 - accuracy: 0.7500
Epoch 7/250
1/1 [==============================] - 0s 2ms/step - loss: 0.5840 - accuracy: 0.7500
Epoch 8/250
1/1 [==============================] - 0s 2ms/step - loss: 0.5837 - accuracy: 0.7500
Epoch 9/250
1/1 [==============================] - 0s 3ms/step - loss: 0.5835 - accuracy: 0.7500
Epoch 10/250
1/1 [==============================] - 0s 1ms/step - loss: 0.5832 - accuracy: 0.7500
Epoch 11/250
1/1 [=========

### Stretch Goal: Activation Functions

Just like anything else, usage of which activation function is determined by the problem itself. One way to optimize your activation function is with parameter tuning using GridSearchCV or RandomizedSearchCV. However, there are problems such as predicting probability between 0 and 1, where sigmoid functions perform best. Again, this is use-case specific.